apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oaimg
resources:
  - tasks/buildah.yaml
  - tasks/git-clone.yaml
  - tasks/golang-build.yaml
  - tasks/golang-test.yaml
  - tasks/openshift-client.yaml
  - pipeline.yaml
